name: rollplay
description: Front-end app that makes use of Roll-API

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  fluro: ^2.0.3
  photo_view: ^0.11.1

  # Logic
  flutter_bloc: ^7.0.0
  http: ^0.13.1
  rollapi: ^1.2.1

  # Platform plugins
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true